### ISSUE TITLE
Allow usage of additional markup builders

### ISSUE THREAD

**Issue by 2bad4u** [Swagger2Markup/markup-document-builder#22]
Hi,
Due to factory using a concrete enum as input it is not possible to add builders for additional markup-languages without modifiying your code. I'd like to use your tool to generate output for Confluence/Jira and it would be really cool to have a simple plugin mechanism.

I've sketched a possible solution (which should not break your existing interface) in 7e0d5bcb31839e1676aff20151364a370864bc16, what do you think?

Regards
André

**Comment by RobWin** [comment]
Hi, thx I have a look at it. Btw, if you like the markup-document-builder, we would love to get your GitHub Star. You can also join the Gitter chat so that we can talk about your PR.

**Comment by RobWin** [comment]
I love the idea to support Confluence/Jira Wiki Markup. But dont they support Markdown as well?
I would prefer to add Confluence to the MarkupLanguage Enum and include your builder into the project instead of adding a plugin mechanism. Because we want to be free to refactor the internals without breaking external plugins which are not in our control. We can also help you to refine your builder and reuse more of our code.

**Comment by 2bad4u** [comment]
Recent Confluence versions support Markdown import but this works not alwasy as expected (e.g. tables are not rendered). For now I think its a good idea to stick to basic Wiki markup that is understood by both Jira and Confluence.

I understand your point of not opening the enum to avoid repsonibility for other's projects. But currently I don't have the time to build and maintain such a builder in a appropriate quality...

**Comment by RobWin** [comment]
Nobody has the time, but that's the advantage of Open Source. If it is valueable many people contribute to the quality of a project. You don't have to maintain by yourself.
